name: Here I am
description: Taye Adeyemi - Programmer · Visionary · Delicious
baseurl: /blog
url: http://taye.me
permalink: pretty
hignligher: pygments
timezone: Europe/Dublin
markdown: kramdown
plugins: [jekyll-feed]

sass:
  style: compressed
